---
title: "Homework 2"
sidebar: false
---

# Required parts

<center>
Due by **Monday, February 5** at midnight.
</center>

<br><br>

**Asynchronous skills challenges**

- **Advanced visualization with ggplot2 - Challenge 2:** Navigate to the challenge on [GitHub](https://classroom.github.com/a/bl30jylw).
- **Advanced map visualization - Challenge 1:** Navigate to this challenge on [GitHub](https://classroom.github.com/a/5W1jLTYy).

<br>

**Preparing for Skills Session 1**

- Skills Session 1 is coming up the week of 2/5. The topic of this session is **keyboard shortcuts**. Keep practicing your keyboard shortcuts this week.
- Visit the [Skills Session 1 page](skills_session1.qmd) for details.


<br><br>


# Optional

If you are aiming for an A in the course, recall from our [syllabus](syllabus.qmd#requirements-for-an-a) that participating in 5 Tidy Tuesday challenges can move you toward this goal.

- For further all-around practice, I encourage you to participate in the most recent [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-01-30/readme.md) challenge.
