---
title: "Skills Session 1"
sidebar: false
---

# Purpose

Get really good with keyboard shortcuts for two main reasons:

- Using shortcuts saves a ton of time
- It feels really cool!

# Task

- Review and practice all shortcuts described [here](https://lmyint.github.io/IntermediateDataSciNotes/keyboard.html).
- During our in-person skills session (week of 2/5-2/9), I will ask you to demonstrate your ability to use most of these shortcuts within a roughly 5 minute span.

# Requirements for passing

You will Pass this Skills Session if you can do all of the commands I ask without using your mouse.

If you forget a few shortcuts, it's ok! Just write down the ones you missed and show them to me the next day.

# Scheduling

Because this is a very short Skills Session (SS), we don't need to formally schedule exact times. Use any of the following options to complete this SS with me:

- Come by my office at any point during these times this week:
    - Monday 2/5: 10:00am-2:30pm, 3:00-4:30pm
    - Wednesday 2/7: 2:30-4:30pm
    - Friday 2/9: noon-4:30pm
- I'll stay after class on Tuesday 2/6 and Thursday 2/8 for 10 minutes (11:10-11:20am).

For just this SS, I can check in with 2 students at a time.
